//Ejercicio 1

let max = 100; //NUMERO MAXIMO QUE SE VA A GENERAR
let min = 1; // NUMERO MINIMO QUE SE VA A GENERAR
let numerom = Math.random()*(max-min) + min; 

while(true){ 
      let usuario = prompt("COLOCA UN NUMERO PARA ADIVINAR EL NUMERO MAGICO"); // EL USUARIO VA A CLOCAR SU NUMERO Y VA A SER COMPARADO CON EL NUMERO MAGICO.

if(usuario == numerom){ //SI EL NUMERO DEL usuario ES IDENTICO (CONSIDERANDO EL NUMERO Y EL TIPO DE NUMERO QUE EN ESTE CASO ES ENTERO) ENTONCES
  alert("HAS GANADO");
  break;
}
else if(usuario == 0){
  break;
}
else if(usuario < numerom){
  // SI EL USUARIO COLOCA UN NUMERO MENOR QUE EL NUMEROM, ENTONCES EL PROGRAMA LE AVISARA CON UNA ALERTA Y PERMITIRA QUE EL USUARIO VUELVA A COLOCAR EL NUMERO HASTA QUE LO ADIVINE GRACIAS AL WHILE(TRUE)
  alert("EL NUMERO ES MENOR QUE EL NUMERO MAGICO, VUELVE A INTENTARLO" );
}
else if(usuario > numerom){
  
  // SI EL USUARIO COLOCA UN NUMERO MAYOR QUE EL NUMEROM, ENTONCES EL PROGRAMA LE AVISARA CON UNA ALERTA Y PERMITIRA QUE EL USUARIO VUELVA A COLOCAR EL NUMERO HASTA QUE LO ADIVINE GRACIAS AL WHILE(TRUE)
  alert("EL NUMERO ES MAYOR QUE EL NUMERO MAGICO, VUELVE A INTENTARLO");
}

} 
